version: '3'
services:
  core:
    build: ./core
    image: openslides
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput"
    depends_on:
      - postgres
    volumes:
      - "staticfiles:/app/personal_data"
    environment:
      # Change according to your details
      REPOSITORY_URL: https://github.com/OpenSlides/OpenSlides.git
      BRANCH: master
      COMMIT_SHA: 03b17837ed2c88692f1b99ec5b9b477f86fdddb6
    networks:
      - back
  web:
    build: ./web
    image: os-web
    links:
      - redis
    depends_on:
      - core
      - nginx
    expose:
      - 8000
    environment:
      # Change according to your details
      VIRTUAL_HOST: 'localhost'
      LETSENCRYPT_HOST: 'localhost'
      LETSENCRYPT_EMAIL: 'localhost'
    volumes:
      - "staticfiles:/app/personal_data"
    networks:
      - back
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: openslides
      POSTGRES_PASSWORD: openslides
      POSTGRES_DB: openslides
    networks:
       - back
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  redis:
    image: redis:alpine
    networks:
      - back
  worker:
    build: ./worker
    image: os-worker
    links:
      - redis
    depends_on:
      - core
    volumes:
      - "staticfiles:/app/personal_data"
    networks:
      - back
  nginx:
    image: jwilder/nginx-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs:/etc/nginx/certs:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_IPV6=true
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - front
      - back
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/etc/nginx/certs:rw"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
    depends_on:
      - nginx
    environment:
      NGINX_PROXY_CONTAINER: nginx
    networks:
      - back
volumes:
  dbdata:
  staticfiles:
  certs:
networks:
  front:
  back:
